name: Python package

on: [push]

jobs:
  build:
    defaults:
      run:
        shell: bash -l {0}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: instanseg
          environment-file: env.yml
      - name: Install
        run: |
          pip install .
      - name: basic smoke test
        run: |
          cd notebooks # because the folder InstanSeg and the module InstanSeg are treated the same (thanks python!)
          python -c 'import InstanSeg'
          python -c 'from InstanSeg.utils.loss.lovasz_losses import binary_xloss'
          python -c 'from InstanSeg.utils.models.InstanSeg_UNet import DecoderBlock, EncoderBlock, conv_norm_act'
      - name: Inference smoke test
        run: |
          wget https://github.com/user-attachments/files/17378191/CMU-1-Small-Region.zip
          unzip CMU-1-Small-Region.zip
          python -c '
            from instanseg import InstanSeg
            instanseg_brightfield = InstanSeg("brightfield_nuclei", image_reader= "tiffslide", verbosity=1)

            labeled_output = instanseg_brightfield.eval(image = CMU-1-Small-Region.tiff",
                                                        save_output = True,
                                                        save_overlay = True)
          '
